version: 0.2

env:
  variables:
    SYSTEM_NAME: example

phases:
  build:
    commands:
      - |
        set -e

        if [ "${BRANCH_NAME}" = "master" ]; then
          Environment_Name="prd"
        elif [ "${BRANCH_NAME}" = "development" ]; then
          Environment_Name="dev"
        fi
        STACK_NAME=${SYSTEM_NAME}-${Environment_Name}-stack-cloudformation
        CHANGE_SET_NAME=${STACK_NAME}-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)

        echo ""
        echo "================================"
        echo "CloudFormation Execution"
        echo "Stack $STACK_NAME"
        echo "ChangeSet $CHANGE_SET_NAME"
        echo "================================"

        aws cloudformation execute-change-set \
          --stack-name ${STACK_NAME} \
          --change-set-name $CHANGE_SET_NAME