AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CommonEnvironmentName:
    Type: String
  CommonSystemName:
    Type: String

Resources:
  SNSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${CommonSystemName}-${CommonEnvironmentName}-iamr-sns"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  